version: "3.8"

services:
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - "8000:8000"
        depends_on: 
            - db
    db:
        image: postgres:13-alpine
        container_name: django_library_docker
        ports:
          - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=django_library